var GAME_LEVELS = [
   ["                                                                                ",
   " !! !!! !  ! !!! xx  xxx xxx x x                                                                ",
   " !  ! ! !! ! ! ! x x x x x   x x    ",
   " !  !!! ! !! ! ! x x xxx xxx xxx     ",
   " !  ! ! !  ! ! ! x x x x   x x x  ",
   " !! ! ! !  ! !!! xx  x x xxx x x        ",
   "",
   "",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                               x        ",
   "x            @                  x         ",
   "xxx  xxxxxxxxxxxxxxxxxxxxxxx  xxx",
   "x                               x           ",
   "x                               x       ",
   "x                               x        ",
   "x                               x",
   "x                               x        ",
   "x                               x        ",
   "x                               x        ",
   "x                               x        ",
   "x      xxx xxx  x  xx  xxx      x                      ",
   "x      x    x  x x x x  x       x  ",
   "x   o  xxx  x  xxx xx   x       x       ",
   "x        x  x  x x x x  x       x       ",
   "x      xxx  x  x x x x  x       x        ",
   "x                               x        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "                                                                                      "],

 ["x                                                                                R                                  ",
   "x  R                               r     xxxxxxxxxxxxxx                                          ",
   "x              R                           xxxx!!xxxx      R                              ",
   "x                                             x!!x                                                           ",
   "x                                             x!!x                                                                ",
   "x                         R                   x!!x        oooo                                  R                ",
   "x                                             x!!x     o        o                                         ",
   "x    T                                        x!!x     x        x                                  o   o         ",
   "x                           	                  vv                                             o   o  o       ",
   "x                                    o o                                                          o              ",
   "x      y                    o        xxxxx             o        o                                      o o ",
   "x                                                      xx      xx                               o      o o    ",
   "x                                        o o                         t	                          o     o       ",
   "x                                                                                                     o     ",
   "x                                       xxxx                              S                      o     o             ",
   "x   @             o    xxxxxxx                     o             xxx                                 oo          ",
   "x                                                  o           xxxxx       xx!!!!!!!                 o          ",
   "xxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxx            o                 ",
   "xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!x     R           o                  ",
   "xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!x         !     o    !      ",
   "xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!x         x       o  x     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!x         x    o     x    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! xxxxxxxxxxxx              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx"],
  ["                                              r          r                       r                                        R           ",
   "                        ",
   "                           ",
   "                                 r ",
   "                               ",
   "                               ",
   "                                                                  r                                  r                               r",
   "                                                ",
   "                  r                           ",
   "                                                                  ",
   "                                                                                                                          r",
   "                                                            ",
   "     Y                                                             r   r               r   r                   r                           ",
   "                                                                     r                   r      ",
   "                                                                                                                 xxxxxxxxxxxxxxxxxxxxxx ",
   "       @                                    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             xxxxxxxxxxxxxxxxxx  x x          ",
   "            $$$$$$$$$$$$$$                        |   o   o |      o   o  o  o   |             o o o        xxxxxxxxxxxxxxxx         x x",
   "              o   o   o                                                         |                                                    x x     ",
   "     o                                                                         |                                                     x x",
   "                             o             xx                       |        |                                                       x x",
   "                                      xxx                                    |                                      o                x x",
   "      xxx                   xxx  xx                                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxx      x x ",
   "      x x                   x x                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxx      x x ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx    x x             ",
   "!!!!!!!!             vvvvv    vvvvvv   vvvvv          v             v     v               v v                                        x x  ",
   "!!!!!!!!!    o  o                                                                                                                    x x  ",
   "!!!!!!!!                                                                                                                             x x  ",
   "!!!!!!!!!!  o    o                                                                                                                   x x  ",
   "!!!!!!!!!    oooo          oo        oo                             o     o             o    o                                       x x  ",
   "!!!!!!!!!xxxxxxxxxxx$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$$$$$$$$$$xxxxxxxxxxxx$$$$$$$$$$$$$$$$$xxxxxxxxxx"],
  ["      r                                                            $$$$$$$$$$$$$$$$$$$$$$$$                 r         r                   ",
   "                                                                       r           R                                     ",
   "                         r                                                                                                        ",
   "                                                        r           r                                                             ",
   "                     r                                                                          r                      ",   
   "     r                       R          x!!!!!!!!!!!!!!!!!!x                                xx       x     x              ",
   "                                        x!!!!!!!!!!!!!!!!!! x                       r                                     ",
   "                                        xv x!!!!!!!!!!!!x v x                                  x                  x     ",
   "                                        x   xxxxxxxxxxxx    x                                               x                     ",   
   "                                     r x                    xx        r                              x                 ",
   "                                       x                                                                                     ",
   "                                     x                                                       r                       x   ",
   "                             R        xx                  xxxxxx!                                 x               z     ",   
   "                                  !!!!xx                        x!!!!                                                                ",
   "                                 !xxxxxxxxx   xxxxxxxxxxxxxxxxxxxx!!!               r                   x      xx        ",
   "                               !!xxxxxx        x                 xx!!!!                                                  ",
   "                      r     !!!xxxxxxxx       =x r                !!!!!!!!!                         x                  @       ",   
   "                          vxxxxxxxxx           x                   xxxx!!!!!                                         xxxxx        ",
   "                           xxxxxxx      xxxxxxxx          r              !!!                                                  ",
   "                           xxxxx               x                         !!!                                     ",
   "          r                xxxxx       =       x                    o    !!!                         r           ",   
   "                           xxx                                    o   o  !!!                                     ",
   "                           xx      xxxxxxxxxx                            !!!                                     ",
   "                           xxxx                                 xxxxxxxxx!!!                                     ",
   "            ooo        S                                                 !!!                                     ",
   "          xxxxxxx                                                         !!!                                    ",
   "                        xxxxxxxxxxxxxxx$$$$$$$$$$$$$$$$$$                  !!!             r                     ",
   "                      !!!!xxx                                               !!!                                  ",
   "                 !!!!!!xxxxx                                        B        xx!!!      !!!!                      ",   
   "               !!!xxxxxxxxxx                                                xxxxxxxxxxxxxx!!!!!               ",
   "             !!xxxxxxxxxxxxx                                                         xxxxxxxxx!!              ",
   "             !xxxxxxxxxxxxxx                                                                  !!           ",
   "          xxxxxxxxxxxxxxxxx                                                                   !!             ",   
   "    !!!!!!!xxxxxxxxxxxx                                                                       !!              ",
   " !!!!!xxxxxx                                                                                  !!!!!!!!!!!!!   ",
   "!!!!xxx                                                            o                            !!!!!!!!!!!!!!!",
   "!!!!!!!!xxxxxxxx                                                                          xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!",   
   "!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   
  ["              Z                                                 ",
   "                                                                                               ",
   "                                                                                                  ",
   "                                                                                                 ",
   "                                                                      ",
   "                                                                                              ",
   "                                                                                               ",
   "                                                                                                  ",
   "                                   @                                                             ",
   "                                 xxx                                                                ",
   "                                                                                           ",
   "                                                                                            ",
   "                                                                                                ",
   "                                                                                                      ",
   "                                                                                                ",
   "                                                                                                 ",
   "                                                                                              ",
   "                                                                                               ",
   "                xxx xxx xxx x x  x xxx                                                                                    ",
   "                x x x   x x x xx x   x                                                                                       ",
   "                xxx x   xxx x x xx  x                                                                                  ",
   "                x x x x x x x x  x  x                                                                                   ",
   "                x x xxx x x x x  x  o                                           ",
   "                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                       "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
